---
title: "3. Differential Abundance - Species Level Table"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(phyloseq)
library(tidyverse)
library(gt)

df1 = readxl::read_xlsx('../Final Outputs/DA Results/DA_Microbiome_Status_All_Univar_Stats.xlsx',sheet = 'Species') %>% 
  select(Species,DA, association_dir, q_val) %>% rename(Direction= association_dir) %>% 
  pivot_wider(names_from = DA, values_from = c(Direction,q_val)) %>% 
  mutate(`Sig (Univar)` = ((`q_val_ANCOM-BC`<0.05) + (q_val_ALDEx2<0.05) + (q_val_Maaslin2<0.05) >1))

df2 = readxl::read_xlsx('../Final Outputs/DA Results/DA_Microbiome_Status_All_Multivar_Stats.xlsx',sheet = 'Species') %>% 
  filter(Variable == 'StatusPD') %>% 
  select(Species,DA, association_dir, p_val) %>% rename(Direction= association_dir) %>% 
  pivot_wider(names_from = DA, values_from = c(Direction,p_val)) %>% 
  mutate(`Sig (Model)` = ((`p_val_ANCOM-BC`<0.05) + (p_val_ALDEx2<0.05) + (p_val_Maaslin2<0.05) >1))

df = df1 %>% left_join(df2 %>% select(Species, `Sig (Model)`))
```

```{r Format Initial Table}
temp = df %>%
  filter(`Sig (Univar)`) %>% # Filter for significant results only
  mutate(Direction = ifelse(`Direction_ANCOM-BC`=='Positive' & `Direction_ALDEx2`=='Positive' & 
                              `Direction_Maaslin2` == 'Positive','Positive',
                            ifelse(`Direction_ANCOM-BC`=='Negative' & `Direction_ALDEx2`=='Negative' & 
                              `Direction_Maaslin2` == 'Negative','Negative',NA))) %>% 
  select(Species,contains('ANCOM-BC'),contains('ALDEx2'),contains('Maaslin2'),Direction,`Sig (Model)`)
names(temp) = c("Species","ANCOM-BC (Dir)", "ANCOM-BC (Qval)", "ALDEx2 (Dir)",
                "ALDEx2 (Qval)","MaAsLin2 (Dir)", "MaAsLin2 (Qval)","Overall Direction","Sig (Model)")
temp[temp=='Positive'] = '+'; temp[temp=='Negative'] = '-'
```

```{r Calculate Log2 FC}
ps = readRDS("../Reference Files/phyloseq_object_leafyadj_absolute_counts.rds") %>% microbiome::transform('compositional') %>% subset_taxa(Species %in% temp$Species) %>% psmelt() %>% 
  group_by(Status,Species) %>% summarize(Abundance = mean(Abundance,na.rm=T),.groups= 'keep') %>% 
  pivot_wider(names_from = Status, values_from = Abundance) %>% 
  mutate(`Log 2 FC` = log2(PD/Ctrl))

temp2 = temp %>% left_join(ps %>% select(Species,`Log 2 FC`)) %>% select(Species, `Log 2 FC`, everything()) %>% 
  arrange(-abs(`Log 2 FC`)) %>% arrange(-`Sig (Model)`) %>% arrange(`Overall Direction`)

temp2$Species = str_remove(temp2$Species,'s__') %>% str_replace_all('_',' ')
```

```{r make pretty with gt}
gt_tbl = temp2 %>% 
  mutate(`# Tools` = (`ANCOM-BC (Qval)`<0.05) + (`ALDEx2 (Qval)`<0.05) + (`MaAsLin2 (Qval)`<0.05)) %>% 
  mutate_if(is.numeric,signif,3) %>% 
  select(Species,`Overall Direction`,`Log 2 FC`,contains('ANCOM'),contains('ALDEx2'),contains("MaAsLin2"),`# Tools`,`Sig (Model)`) %>% 
  gt() %>% 
  tab_row_group(label = md('**Elevated in PD**'),rows = (`Overall Direction` == '+')) %>% 
  tab_row_group(label = md('**Reduced in PD**'),rows = (`Overall Direction` == '-')) %>% 
  cols_hide(c('Overall Direction')) %>% 
  tab_spanner('ANCOM-BC',columns = contains('ANCOM-BC')) %>% 
  tab_spanner('ALDEx2',columns = contains('ALDEx2')) %>% 
  tab_spanner('MaAsLin2',columns = contains('MaAsLin2')) %>% 
  cols_label(
    `ANCOM-BC (Dir)` = "Dir",
    `ANCOM-BC (Qval)` = 'Qval',
    `ALDEx2 (Dir)` = "Dir",
    `ALDEx2 (Qval)` = 'Qval',
    `MaAsLin2 (Dir)` = "Dir",
    `MaAsLin2 (Qval)` = 'Qval'
  ) %>%
  cols_align('center',-Species) %>% 
  tab_options(column_labels.font.weight = 'bold') %>% 
  tab_style(
    style = cell_text(style = "italic"),
    locations = cells_body(
      columns = `ANCOM-BC (Qval)`,
      rows = `ANCOM-BC (Qval)` >=0.05
    )
  ) %>% 
  tab_style(
    style = cell_text(style = "italic"),
    locations = cells_body(
      columns = `ALDEx2 (Qval)`,
      rows = `ALDEx2 (Qval)` >=0.05
    )
  ) %>% 
  tab_style(
    style = cell_text(style = "italic"),
    locations = cells_body(
      columns = `MaAsLin2 (Qval)`,
      rows = `MaAsLin2 (Qval)` >=0.05
    )
  )
gt_tbl
# Manually save the html as a PDF
gtsave(gt_tbl,filename = "../Final Outputs/DA Results/Species table.html")
```